#!/usr/bin/env bash
# Configures Nginx with a custom HTTP response header X-Served-By
# shellcheck disable=SC2154

# Update and install Nginx
apt-get update
apt-get install -y nginx

# Create pages
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error404.html

# Configure Nginx
printf %s "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html;
        error_page 404 /error404.html;

        server_name _;
        
        add_header X-Served-By \$hostname;
        
        location / {
                try_files \$uri \$uri/ =404;
        }
        
        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}
" > /etc/nginx/sites-available/default

# Test and restart
nginx -t
service nginx restart