#!/usr/bin/env bash
# Installs and configures HAProxy for load balancing

# Update and install HAProxy
sudo apt update -y
sudo apt install haproxy -y

# Enable HAProxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Backup original config
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Create HAProxy configuration
printf %s 'global
        log /dev/log local0
        log /dev/log local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000

frontend http-in
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 6855-web-01 3.86.143.160:80 check
        server 6855-web-02 54.174.119.2:80 check
' | sudo tee /etc/haproxy/haproxy.cfg

# Restart HAProxy
sudo service haproxy restart

# Verify HAProxy is running
sudo service haproxy status

echo "HAProxy configured successfully"