#!/usr/bin/env bash
# Installs and configures Nginx web server
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart