#!/usr/bin/env bash
# Configures Nginx with a redirect using sed substitute
# Install nginx
apt-get update -y
apt-get install nginx -y

echo "Holberton School" > /var/www/html/index.html

sed -i "s#index index.html;.*#index index.html;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}#" /etc/nginx/sites-available/default

service nginx restart