#!/usr/bin/env bash
# Configures Nginx with a redirect

apt-get update -y
apt-get install nginx -y

echo "Holberton School" > /var/www/html/index.html

printf %s "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html;

        server_name _;

        location /redirect_me {
           return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}
" > /etc/nginx/sites-available/default

service nginx restart