#!/usr/bin/env bash
# Configures Nginx with a custom 404 page

# Update and install nginx
apt-get update -y
apt-get install nginx -y

# Create index.html
echo "Holberton School" > /var/www/html/index.html

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/error404.html

# Configure nginx with custom 404 page and redirect
printf %s "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html;
        error_page 404 /error404.html;

        server_name _;

        location /redirect_me {
           return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}
" > /etc/nginx/sites-available/default

# Restart nginx
service nginx restart